# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from usuarios import usuario_pb2 as usuarios_dot_usuario__pb2


class UserServiceStub(object):
    """===== SERVICE =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/gestionusuarios.UserService/CreateUser',
                request_serializer=usuarios_dot_usuario__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=usuarios_dot_usuario__pb2.CreateUserResponse.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/gestionusuarios.UserService/UpdateUser',
                request_serializer=usuarios_dot_usuario__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=usuarios_dot_usuario__pb2.UpdateUserResponse.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/gestionusuarios.UserService/DeleteUser',
                request_serializer=usuarios_dot_usuario__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=usuarios_dot_usuario__pb2.DeleteUserResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/gestionusuarios.UserService/GetUser',
                request_serializer=usuarios_dot_usuario__pb2.GetUserRequest.SerializeToString,
                response_deserializer=usuarios_dot_usuario__pb2.GetUserResponse.FromString,
                )
        self.ListUsers = channel.unary_unary(
                '/gestionusuarios.UserService/ListUsers',
                request_serializer=usuarios_dot_usuario__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=usuarios_dot_usuario__pb2.ListUsersResponse.FromString,
                )


class UserServiceServicer(object):
    """===== SERVICE =====
    """

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=usuarios_dot_usuario__pb2.CreateUserRequest.FromString,
                    response_serializer=usuarios_dot_usuario__pb2.CreateUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=usuarios_dot_usuario__pb2.UpdateUserRequest.FromString,
                    response_serializer=usuarios_dot_usuario__pb2.UpdateUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=usuarios_dot_usuario__pb2.DeleteUserRequest.FromString,
                    response_serializer=usuarios_dot_usuario__pb2.DeleteUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=usuarios_dot_usuario__pb2.GetUserRequest.FromString,
                    response_serializer=usuarios_dot_usuario__pb2.GetUserResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=usuarios_dot_usuario__pb2.ListUsersRequest.FromString,
                    response_serializer=usuarios_dot_usuario__pb2.ListUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gestionusuarios.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """===== SERVICE =====
    """

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gestionusuarios.UserService/CreateUser',
            usuarios_dot_usuario__pb2.CreateUserRequest.SerializeToString,
            usuarios_dot_usuario__pb2.CreateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gestionusuarios.UserService/UpdateUser',
            usuarios_dot_usuario__pb2.UpdateUserRequest.SerializeToString,
            usuarios_dot_usuario__pb2.UpdateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gestionusuarios.UserService/DeleteUser',
            usuarios_dot_usuario__pb2.DeleteUserRequest.SerializeToString,
            usuarios_dot_usuario__pb2.DeleteUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gestionusuarios.UserService/GetUser',
            usuarios_dot_usuario__pb2.GetUserRequest.SerializeToString,
            usuarios_dot_usuario__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gestionusuarios.UserService/ListUsers',
            usuarios_dot_usuario__pb2.ListUsersRequest.SerializeToString,
            usuarios_dot_usuario__pb2.ListUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
