# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuarios.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'usuarios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eusuarios.proto\x12\x08usuarios\"\x81\x01\n\x13\x43rearUsuarioRequest\x12\x15\n\rnombreUsuario\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08\x61pellido\x18\x03 \x01(\t\x12\x10\n\x08telefono\x18\x04 \x01(\t\x12\x12\n\nemailUnico\x18\x05 \x01(\t\x12\x0b\n\x03rol\x18\x06 \x01(\t\"\xa1\x01\n\x17ModificarUsuarioRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rnombreUsuario\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x10\n\x08\x61pellido\x18\x04 \x01(\t\x12\x10\n\x08telefono\x18\x05 \x01(\t\x12\x12\n\nemailUnico\x18\x06 \x01(\t\x12\x0b\n\x03rol\x18\x07 \x01(\t\x12\x0e\n\x06\x65stado\x18\x08 \x01(\t\" \n\x12\x42\x61jaUsuarioRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\"\n\x0fUsuarioResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"4\n\x0cLoginRequest\x12\x15\n\ridentificador\x18\x01 \x01(\t\x12\r\n\x05\x63lave\x18\x02 \x01(\t\"X\n\rLoginResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x15\n\rnombreUsuario\x18\x02 \x01(\t\x12\x12\n\nemailUnico\x18\x03 \x01(\t\x12\x0b\n\x03rol\x18\x04 \x01(\t2\xae\x02\n\x0eUsuarioService\x12H\n\x0c\x43rearUsuario\x12\x1d.usuarios.CrearUsuarioRequest\x1a\x19.usuarios.UsuarioResponse\x12P\n\x10ModificarUsuario\x12!.usuarios.ModificarUsuarioRequest\x1a\x19.usuarios.UsuarioResponse\x12\x46\n\x0b\x42\x61jaUsuario\x12\x1c.usuarios.BajaUsuarioRequest\x1a\x19.usuarios.UsuarioResponse\x12\x38\n\x05Login\x12\x16.usuarios.LoginRequest\x1a\x17.usuarios.LoginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuarios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREARUSUARIOREQUEST']._serialized_start=29
  _globals['_CREARUSUARIOREQUEST']._serialized_end=158
  _globals['_MODIFICARUSUARIOREQUEST']._serialized_start=161
  _globals['_MODIFICARUSUARIOREQUEST']._serialized_end=322
  _globals['_BAJAUSUARIOREQUEST']._serialized_start=324
  _globals['_BAJAUSUARIOREQUEST']._serialized_end=356
  _globals['_USUARIORESPONSE']._serialized_start=358
  _globals['_USUARIORESPONSE']._serialized_end=392
  _globals['_LOGINREQUEST']._serialized_start=394
  _globals['_LOGINREQUEST']._serialized_end=446
  _globals['_LOGINRESPONSE']._serialized_start=448
  _globals['_LOGINRESPONSE']._serialized_end=536
  _globals['_USUARIOSERVICE']._serialized_start=539
  _globals['_USUARIOSERVICE']._serialized_end=841
# @@protoc_insertion_point(module_scope)
